#ifndef __STRAP__H__
#define __STRAP__H__

// INTR
#define INTR_MASK 0xaaa

#define S_INTR_MASK 0x222
#define S_SOFTWARE_INTR 0x2
#define S_TIMER_INTR 0x20
#define S_EXTERNAL_INTR 0x200

#define M_INTR_MASK 0x888
#define M_SOFTWARE_INTR 0x8
#define M_TIMER_INTR 0x80
#define M_EXTERNAL_INTR 0x800

// EXCEPTION
#define EXC_MASK 0xbbff
#define INSTRUCTION_ADDRESS_MISALIGNED_EXC 0x1
#define INSTRUCTION_ACCESS_FAULT_EXC 0x2
#define ILLEGAL_INTSTRUCTION_EXC 0x4
#define BREAK_POINT_EXC 0x8
#define LOAD_ADDRESS_MISALIGNED_EXC 0x10
#define LOAD_ACCESS_FAULT_EXC 0x20
#define STORE_AMMO_ADDRESS_MISALIGNED_EXC 0x40
#define STORE_AMMO_ACESS_FAULT_EXC 0x80
#define ENVIRONMENT_CALL_FROM_U_MODE_EXC 0x100
#define ENVIRONMENT_CALL_FROM_S_MODE_EXC 0x200
#define ENVIRONMENT_CALL_FROM_M_MODE_EXC 0x800
#define INSTRUCTION_PAGE_FAULT 0x1000
#define LOAD_PAGE_FAULT 0x2000
#define STORE_AMMO_PAGE_FAULT 0x8000

void stvec();

void strap_handler();

void strap_init();

#endif 